name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Runs on push to the main branch
  pull_request:
    branches:
      - main # Runs on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures deployment happens only if build succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production server
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}  # Store your private key securely in GitHub Secrets
        run: |
          echo "Deploying application to server..."
          ssh -i $DEPLOY_KEY user@your-server "cd /path/to/your/project && git pull origin main && npm install && pm2 restart app"
